### PR TITLE
Work on default config in the app

### LINKED ISSUE #313: Change default config feature to allow missing values
This is result in a crash some day, so let's fix this before we forget!

### PR DESCRIPTION
**Pull request by adriaandotcom**
Something like this? TypeScript is fighting me :)

Fix https://github.com/BustByte/coronastatus/issues/313

### CODE REVIEW

**Comment by adriaandotcom** [comment]
Can't see what I'm doing wrong here:

CleanShot 2020-03-25 at 16 35 51@2x

**Comment by fossecode** [comment]
I can look into it in a couple of minutes

**Comment by fossecode** [comment]
Had to create a new PR since the build process on this one has been stuck for 3 hours now.
Fixed in https://github.com/BustByte/coronastatus/pull/330

**Comment by adriaandotcom** [comment]
😢

**Pull request closed without merging**
