### PR TITLE
fix: Celsius spelling

### PR DESCRIPTION
**Pull request by mihai-sysbio**
[Celsius scale](https://en.wikipedia.org/wiki/Celsius)

### CODE REVIEW

**Comment by fossecode** [comment]
@mihai-sysbio thanks for the PR! Could you please let the keys in the json-files be the same, and only fix the actual translations? 😄 We have many languages in progress that are not merged to master, and it will be cumbersome for them if the keys change.

**Review by fossecode — CHANGES_REQUESTED** [review]
Check out comment ☝️

**Comment by mihai-sysbio** [comment]
Sure, though I guess that will continue to propagate the misspell to all future languages.. wouldn't it be safer to resolve the conflicts once they occur?

**Comment by fossecode** [comment]
Problem is that they won't even get conflicts (since it is a new file), they will just be missing a key. When people translate they usually first make a copy of the english locale and then change the values, so hopefully they will look at the correct spelling 😅Should be easier to refactor once all translations are finished.

**Review by fossecode — APPROVED** [review]
Awesome, thanks 👍

**Pull request merged**
