### PR TITLE
Argentina

### PR DESCRIPTION
**Pull request by waltergammarota**
I have deployed a version to Argentina. 
You can check it on http://coronastatus.com.ar
Thanks!

### CODE REVIEW

**Review by fossecode — CHANGES_REQUESTED** [review]
Hi, thanks for translating Argentina 👍Could you fix the merge conflict and delete `package-lock.json`? We use `yarn` instead.

**Comment by fossecode** [comment]
Could you also rename the locale and the files to `es-AR`? Just refactored it for all the other locales :) You can change the casing in git using `git mv es-ar.json es-AR.json` etc

**Comment by fossecode** [comment]
Git is case insensitive, so in order to get git to understand that the filenames have changed casing, you need to use `git mv es-ar.json es-AR.json` (with git first). Otherwise you might get problems when deploying to production.

I think you can also revert the changes to `yarn.lock`, this file should not be changed unless you have changes in `package.json`

**Comment by waltergammarota** [comment]
Can you check it now?

**Comment by fossecode** [comment]
Did you mean to close it?

**Comment by waltergammarota** [comment]
I will restart everything on a new request. 
I am sorry for the mess. I am not used to work with teams.
Just cleaning everything and I will make a pull request again.
Thanks!

**Comment by fossecode** [comment]
No problem, it is a great way to learn something new for all of us :)

**Pull request closed without merging**
