### PR TITLE
Form design tweaks

### PR DESCRIPTION
**Pull request by jinjie**
#393 

- Removed black border from dropdown
- Checkbox and radio button matches theme

### CODE REVIEW

**Comment by jinjie** [comment]
Question: Why am I seeing so many commits in one PR? Those were already merged into master. Am I doing anything wrong?

**Comment by fossecode** [comment]
> Question: Why am I seeing so many commits in one PR? Those were already merged into master. Am I doing anything wrong?

It is probably because the commit id's change when we squash and merge, so git does not understand that the commits are already on master. You could reset your fork after a PR has been merged, https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream

**Review by fossecode — APPROVED** [review]

**Comment by jinjie** [comment]
Thank you for the explanation.

Regards,
Kong Jin Jie

**Review by amritnagi — CHANGES_REQUESTED** [review]
Great work... two minor changes if possible:
* Report.ejs - line 81, add class="appearance-none rounded focus:outline-none focus:shadow-outline"
(this will trigger the focus state when tabbing through)

* Report.ejs - line 211 / 408 - change py-2 to py-3

**Comment by fossecode** [comment]
@jinjie do you have time to complete this? 😄

**Comment by jinjie** [comment]
> Report.ejs - line 211 / 408 - change py-2 to py-3

Line numbers are different, but I figured that it is for postal and temperature field.

> Report.ejs - line 81, add class="appearance-none rounded focus:outline-none focus:shadow-outline"

Don't understand this instruction, not sure if the line numbers are different.

**Comment by amritnagi** [comment]
Hey, i meant just adding the classes to this element `<select required name="age" id="Age">`

so: `<select class="appearance-none rounded focus:outline-none focus:shadow-outline" required name="age" id="Age">`

**Comment by amritnagi** [comment]
@fossecode - do you know who did the custom checkboxes?  
Could you ask them to look at adding focus styles on them? As you don't see which element is selected when tabbing through using the keyboard (and i couldn't get it to work)

**Comment by jinjie** [comment]
Just wondering will this work for the focus?

Screenshot 2020-03-30 at 3 11 48 PM

**Comment by amritnagi** [comment]
YES!! Can you get that to work on the checkboxes too?

**Comment by jinjie** [comment]
> YES!! Can you get that to work on the checkboxes too?

Working on it... Checkbox seems a little tricky.

**Comment by jinjie** [comment]
Please check. 😄

**Comment by fossecode** [comment]
> @fossecode - do you know who did the custom checkboxes?
> Could you ask them to look at adding focus styles on them? As you don't see which element is selected when tabbing through using the keyboard (and i couldn't get it to work)

Not really sure, we just used a template in the first version. Don't know if you guys changed them when implementing the new design?

**Review by fossecode — APPROVED** [review]

**Comment by fossecode** [comment]
Should we merge this? 😄 @amritnagi

**Review by amritnagi — APPROVED** [review]

**Comment by amritnagi** [comment]
All good from me! :)

**Comment by fossecode** [comment]
Awesome, great work @jinjie

**Pull request merged**
