### PR TITLE
[WIP] Add UA locale

### PR DESCRIPTION
**Pull request by tarasmatsyk**
This is a WIP, help is welcome

### CODE REVIEW

**Comment by fossecode** [comment]
@tarasmatsyk added postal codes and municipalities: https://github.com/BustByte/coronastatus/pull/334

**Comment by fossecode** [comment]
There are a couple of new sentences incoming, remember to add them as well: https://github.com/BustByte/coronastatus/pull/373

**Comment by tarasmatsyk** [comment]
I am testing translations right now, will add new ones too. Thanks for heads up @fossecode

**Comment by tarasmatsyk** [comment]
@fossecode I love new hashtags and answers. Ukraine is ready, I am working on hosting

**Review by fossecode — APPROVED** [review]
Great work!

**Pull request merged**
