### PR TITLE
Simplify docker development environment

### PR DESCRIPTION
**Pull request by sbocinec**
This PR simplifies and fixes the docker development workflow.

## CHANGES

*BREAKING CHANGES* -  devs using docker for development might have slitghtly changed workflow as this PR:
* Remove `Dockerfile`
* Modify `docker-compose.yml`

## Details
The original `Dockerfile` I created appeared to be redundant and not needed, as it doesn't bring any benefits: 
* node modules were installed into the `node_modules` during the docker image build, what is not needed and rather bad practice as during the development we are reinstalling the modules often = wasted space
* we can simply use the _vanilla_ node docker image without building our own image.

### CODE REVIEW

**Review by fossecode — APPROVED** [review]
Looks good to me! Does any of you know about any others that use docker in prod that needs to be notified?

**Comment by michaelmcmillan** [comment]
Nice! I've made some changes to the Dockerfile myself, I guess they're pretty much the same:

```
FROM node:lts-buster-slim

RUN mkdir /app

COPY package.json yarn.lock
COPY . .

WORKDIR /app
RUN yarn
CMD yarn start
```

Can you tag images using compose? I've been toying around with a k8s cluster – would need to be able to tag builds to keep it under control :)

**Review by michaelmcmillan — APPROVED** [review]

**Comment by sbocinec** [comment]
> Can you tag images using compose? I've been toying around with a k8s cluster – would need to be able to tag builds to keep it under control :)

@michaelmcmillan  - in the development docker compose I'm suggesting here, there is actually no build step, it only mounts the application directory inside and run the `yarn dev` command. So as there is no build step, there is no new image produced = no tagging possible. This makes it super simple for the development on your own machine on top of the constantly chaning files in the app directory, but definitely not suitable for production as there the image has to be built with the app source code and the node_modules inside the image, exactly as you are doing.

And yeah, using your Dockerfile, docker compose can tag images on build, eg.:
```
...
services:
  app:
    build: .
    image: coronastatus:${VERSION:-latest}
...
```
And then running `docker-compose build` will also tag the image with the `$VERSION` or `latest` tag

**Comment by sbocinec** [comment]
> Looks good to me! Does any of you know about any others that use docker in prod that needs to be notified?

@fossecode nope, I'm not aware of anyone else who is running it in docker in production.

As these changes are aimed to ease development, I think it's safe to LGTM :-)

**Comment by michaelmcmillan** [comment]
Aha, now I see how it works. Didn't know that was possible!

LGTM 👍

**Pull request merged**
