### PR TITLE
localizing some malta links/strings

### PR DESCRIPTION
**Pull request by tkrunning**

### CODE REVIEW

**Comment by fossecode** [comment]
Seems like there are a few changes that should not be here?

**Comment by fossecode** [comment]
@tkrunning which of the commits are supposed to be part of the PR?

**Comment by tkrunning** [comment]
@fossecode Oh, shoot, not sure what happened. It's only the last one (change name of health service, info link).

Are you able to only accept those changes or should I delete this and try again?

**Comment by fossecode** [comment]
I can pick it manually :)

**Comment by fossecode** [comment]
Fixed in #485

**Pull request closed without merging**
