### PR TITLE
add translations for en-US

### PR DESCRIPTION
**Pull request by fossecode**

### CODE REVIEW

**Comment by michaelmcmillan** [comment]
I think I just fixed this with this PR? https://github.com/BustByte/coronastatus/pull/377

**Comment by fossecode** [comment]
No you forgot the translations

**Comment by fossecode** [comment]
It uses the text in the function call as fallback

**Comment by michaelmcmillan** [comment]
ooh woopsie

**Review by michaelmcmillan — APPROVED** [review]

**Pull request merged**
