### PR TITLE
Move the facebook button and resize the github logo

### PR DESCRIPTION
**Pull request by zerbfra**
This moves the facebook button and resizes the github logo

### CODE REVIEW

**Comment by fossecode** [comment]
Could you add a screenshot of the changes?

**Comment by fossecode** [comment]
Sorry I misclicked

**Comment by zerbfra** [comment]
Schermata 2020-03-25 alle 22 00 58
Schermata 2020-03-25 alle 22 00 51

**Comment by fossecode** [comment]
I think it looks good, but we should also check with the designer 😄@amritnagi, thoughts?

**Comment by zerbfra** [comment]
I think it's more clear, since previously it seemd to tell "share on facebook your compiled form" lol - it was not soo good ;)

**Comment by amritnagi** [comment]
Looks good to me... I think we do need to revisit share and add more options, but not super critical at the moment

**Review by fossecode — APPROVED** [review]

**Pull request merged**
