### PR TITLE
Add other contributors, fix repo link

### PR DESCRIPTION
**Pull request by sbocinec**
* Add other known contributors 
* Fix git repo link

### CODE REVIEW

**Review by fossecode — APPROVED** [review]
Awesome, thanks! Would it be cool to include flags in front of the names in order to show that people from all over the world has contributed? :) https://emojipedia.org/flags/

**Comment by fossecode** [comment]
````
    <li class="contributor-list">🇳🇴Kristoffer Sundmyhr</li>
    <li class="contributor-list">🇳🇴Jan Magne Andersen</li>
    <li class="contributor-list">🇳🇴Arild Øren Wanvik</li>
    <li class="contributor-list">🇳🇴Marius Kalvø</li>
    <li class="contributor-list">🇳🇴Rina Andriana</li>
    <li class="contributor-list">🇳🇴William Benjamin Rode</li>
    <li class="contributor-list">🇳🇴Kai H T Mortensen-Langhaug</li>
    <li class="contributor-list">🇳🇴Kåre Digernes</li>
    <li class="contributor-list">🇳🇱Adriaan van Rossum</li>
    <li class="contributor-list">🇬🇧Amrit Nagi</li>
    <li class="contributor-list">🇳🇴Eirik Fosse</li>
    <li class="contributor-list">🇮🇹Francesco Zerbinati</li>
    <li class="contributor-list">🇳🇱Kilian Valkhof</li>
    <li class="contributor-list">🇨🇭Luke Seelenbinder</li>
    <li class="contributor-list">🇳🇴Michael McMillan</li>
    <li class="contributor-list">🇫🇷Raphaëlle Bertrand-Lalo</li>
    <li class="contributor-list">🇸🇰Stano Bocinec</li>
    <li class="contributor-list">🇺🇦Taras Matsyk</li>
````

**Review by adriaandotcom — CHANGES_REQUESTED** [review]
Let’s add those flags indeed!

**Comment by sbocinec** [comment]
Thanks for the perfect idea! Flags added.

**Review by adriaandotcom — APPROVED** [review]

**Pull request merged**
