### PR TITLE
Removed count from Facebook button

### PR DESCRIPTION
**Pull request by clirette**
PR for #395

### CODE REVIEW

**Comment by michaelmcmillan** [comment]
I feel the button brings [social proof ](https://en.wikipedia.org/wiki/Social_proof) to the site, but I might be wrong. Maybe we should a/b test it before removing it?

**Review by fossecode — APPROVED** [review]
Thanks! :)

**Comment by michaelmcmillan** [comment]
Should we completely remove it @fossecode?

**Comment by fossecode** [comment]
@michaelmcmillan didn't see your message before now. Yeah I liked the number as well, but we should not display a fake number. The button is still there, but without the number. If we want the number there, we should either use the button from Facebook, or use an API to get the count (from the backend, and cache it for a while).

Looks kinda weird when new sites were set up and had 10 submissions, but 1,7k Facebook shares

**Pull request merged**
