### PR TITLE
add voluntary isolation as form option

### PR DESCRIPTION
**Pull request by tkrunning**
# Translations needed
## Text
* March 28
* In voluntary isolation to avoid potentially spreading or catching COVID-19

## Languages done
If you don't know how to add these changes in this PR, just write the translations in the comments.

* [ ]  .bd – Bangladesh (@redikod)
* [x]  .ca – Canada (@mepa1363)
* [x]  .dk – Denmark (@btutal)
* [x]  .en-AU – Australia (@bitbonsai)
* [x]  .en-IN – India
* [x]  .en-MT – Malta (@tkrunning)
* [x]  .en-NG – Nigeria (@desoga10)
* [x]  .en-SG – Singapore (@jinjie)
* [x]  .en-US – United States
* [x]  .en – United Kingdom (@amritnagi)
* [x]  .es-AR – Argentina (@waltergammarota)
* [x]  .es-CL – Chili (@rubentd)
* [x]  .es-CO – Colombia (@julianbetancourt)
* [x]  .es-ES – Spain (@jesgarciamartinez)
* [x]  .es-MX – Mexico (@alexalmadav) 
* [x]  .fr-FR – France (@bertrandlalo)
* [x]  .it – Italy
* [x]  .ms-MY – Malaysia (@jinjie)
* [x]  .nl – The Netherlands (@adriaanvanrossum @Kilian h@NickolasBoyer @julianbetancourt)
* [x]  .no – Norway (@michaelmcmillan @fossecode)
* [x]  .se – Sweden (@pontus @mihai-sysbio @MalinAhlberg @talavis)
* [x]  .sk – Slovakia (@sbocinec)
* [x]  .tr – Turkey (@btutal)
* [x]  .ua – Ukraine (@tarasmatsyk)
* [x]  .pt-PT – Portugal (@andrezzoid @Painatalman)
* [ ]  .de-DE – Germany (@btutal @lseelenbinder)
* [ ]  .ch-DE – Switzerland (@lseelenbinder)

### CODE REVIEW

**Comment by tarasmatsyk** [comment]
UA version:
```
"March 28": "Березень 28",
  "In voluntary isolation to avoid potentially spreading or catching COVID-19": "На самокарантині, щоб зменшити поширення або уникнути COVID-19",
```

@tkrunning

**Comment by bertrandlalo** [comment]
**fr-FR**
---------
- **March 28:** 28 Mars
- **In voluntary isolation to avoid potentially spreading or catching COVID-19:** 
En isolement volontaire pour éviter de propager le COVOD-19 ou d'être contaminé

**Comment by adriaandotcom** [comment]
NL:

- 28 maart
- Vrijwillige zelfisolatie

**Comment by pontus** [comment]
SE:

```
"March 28:": "28 mars",
"In voluntary isolation to avoid potentially spreading or catching COVID-19": "Frivilligt isolerad för att undgå möjlig spridning eller att bli smittad av COVID-19"
```

**Review by adriaandotcom — APPROVED** [review]

**Comment by julianbetancourt** [comment]
# Spanish

- Applies for `es-CO`, `es-AR`, `es-ES`, `es-CL`, `es-MX` 

```
"March 28": "Marzo 28",
  "In voluntary isolation to avoid potentially spreading or catching COVID-19": "En aislamiento voluntario para evitar una potencial propagación o ser contagiado de COVID-19"
}
```

**Comment by sbocinec** [comment]
SK translation:
```
"March 28": "28. marca",
"In voluntary isolation to avoid potentially spreading or catching COVID-19": "V dobrovoľnej karanténe, vyhnúť sa tak možnému šíreniu alebo infikovaniu COVID-19",
```

**Review by adriaandotcom — APPROVED** [review]

**Comment by adriaandotcom** [comment]
I fixed this PR in https://github.com/BustByte/coronastatus/pull/475 so we can merge it from there.

**Comment by adriaandotcom** [comment]
Oops, closed the wrong one.

**Review by fossecode — APPROVED** [review]

**Pull request merged**
