### PR TITLE
Fallback from env

### PR DESCRIPTION
**Pull request by zerbfra**
This adds fallback from env (useful for heroku)

### CODE REVIEW

**Comment by zerbfra** [comment]
This is the major change
https://github.com/BustByte/coronastatus/pull/359/commits/6b0697e05d06daaf6a41520b2b8007da809ba879

**Comment by adriaandotcom** [comment]
Great work! A few issues with the linter, could you fix those?

**Comment by fossecode** [comment]
Could you also try to rebase on `BustByte:master` or reset? The commits are getting pretty messy at this point, hard to review :)

**Comment by zerbfra** [comment]
Going to fix everything

**Pull request closed without merging**
