### PR TITLE
a11y improvements

### PR DESCRIPTION
**Pull request by Kilian**
work-in-progress for improving the CSS and HTML to be more accessible. Todo in #312

### CODE REVIEW

**Comment by Kilian** [comment]
new colors:
localhost_7272 Desktop Wide_polypane

**Review by fossecode — APPROVED** [review]

**Comment by michaelmcmillan** [comment]
fantastic work 👍

**Comment by Kilian** [comment]
Ready to be reviewed and merged :)

**Comment by fossecode** [comment]
LGTM, just go ahead and merge 👍

**Review by fossecode — APPROVED** [review]

**Pull request merged**
