### PR TITLE
added swedish postcodes and coordinates

### PR DESCRIPTION
**Pull request by michaelmcmillan**

### CODE REVIEW

**Comment by ewels** [comment]
Brilliant stuff, thank you @michaelmcmillan! 🙌

**Comment by jhagberg** [comment]
Just for interested what is the data source and script?

**Comment by michaelmcmillan** [comment]
@jhagberg: Just left a comment on the issue you made.

> The file you referenced [SE.zip](http://download.geonames.org/export/zip/SE.zip) is what we feed [this script](https://github.com/BustByte/coronastatus/blob/master/app/locales/geonames-converter.py) in our repo ☺️

**Comment by jhagberg** [comment]
Thanks LGTM!

**Review by fossecode — APPROVED** [review]

**Pull request merged**
