### PR TITLE
Add prettier workflow to fix #228

### LINKED ISSUE #228: Add prettier to gh-workflow
Example: https://github.com/simpleanalytics/scripts/blob/master/.github/workflows/nodejs.yml

### PR DESCRIPTION
**Pull request by michaelmcmillan**

### CODE REVIEW

**Comment by fossecode** [comment]
I prefer that it fails rather than trying to fix the commits, but open for discussion.

**Comment by michaelmcmillan** [comment]
any disadvantage of linting with an extra commit on the pr?

**Comment by fossecode** [comment]
Messy git history, but that can be solved if we squash when merging. I also like to know what changes the linter makes, as linters can make mistakes (I think that happend here? https://github.com/BustByte/coronastatus/pull/221).

**Comment by michaelmcmillan** [comment]
aight, let's stick with failing

**Comment by adriaandotcom** [comment]
> Messy git history, but that can be solved if we squash when merging. I also like to know what changes the linter makes, as linters can make mistakes (I think that happend here? #221).

Jep, that was failing indeed.

**Comment by adriaandotcom** [comment]
If we want to prevent that error from happening we could use ``<%= __(`string long...`) ...``

**Review by fossecode — APPROVED** [review]

**Pull request merged**
