### PR TITLE
Generate social images

### PR DESCRIPTION
**Pull request by Kilian**
PR for #352. 

On /social-images there's now the og image, a banner and the twitter header

todo:
- [x] generate pngs from these using puppeteer
- [x] automatically place them in the right folder for a language
- [x] hide the page in production
- [x] add documentation
- [x] use config.ts instead of config.json
- [x] fittext for the title

### CODE REVIEW

**Comment by Kilian** [comment]
Implemented a preference for LOCALE as being built in #351.

**Comment by Kilian** [comment]
## Generated images:

### Banner
banner

### Sharing image
social-media

### Twitter header image
twitter-header

**Review by fossecode — APPROVED** [review]
Cool!

**Comment by fossecode** [comment]
Btw, consider using config from `app/config.ts` instead

**Review by amritnagi — APPROVED** [review]
Brilliant stuff, looks great to me!

**Comment by amritnagi** [comment]
Just a thought, have you tested it with all of the localised strings?

**Comment by Kilian** [comment]
@amritnagi I haven't but it's a flex layout in HTML so:

* the tagline can wrap to newlines and since it's a flex layout in all, it'll still be centered in the image
* the button expands as needed to fit the content

@fossecode I'll get it from there!

**Comment by michaelmcmillan** [comment]
insane!

**Comment by jinjie** [comment]
website address got cut off when too long.

Screenshot 2020-03-27 at 9 06 58 PM

**Comment by amritnagi** [comment]
@Kilian What if we convert the text to a svg?
This kind of thing: https://codepen.io/chriscoyier/pen/zaRxdm

**Comment by Kilian** [comment]
Good idea for the title!

We should also do a second flexbox layout in the banner so the text floats to the left if the button is too wide.

**Comment by adriaandotcom** [comment]
This is still a WIP, right @Kilian?

**Comment by Kilian** [comment]
Yes, I want to get the fitted text in before merging. 

We can also merge it now and tell people to check them though, and fix that later.

**Comment by Kilian** [comment]
Code now uses `config.ts` and fits the title automatically. ready for test + merge.

**Review by fossecode — APPROVED** [review]

**Comment by adriaandotcom** [comment]
What is the size of the images the we output? In pixels and bytes? Because they can be quite big when directly from puppeteer I think. Maybe we should put them on a CDN or something instead of in this repo. What do you think?

**Comment by michaelmcmillan** [comment]
Now that we've moved around the directories and config field I think we need to update this PR as well

**Comment by tarasmatsyk** [comment]
Looking forward to this PR :)

**Comment by fossecode** [comment]
I can make the necessary changes in order to get this working with the new config

**Review by fossecode — APPROVED** [review]

**Pull request merged**
