### PR TITLE
Modernize design a bit

### PR DESCRIPTION
**Pull request by adriaandotcom**
Just a few spacing modifications (before vs after):

Screenshot Screenshot

Let me know if this is acceptable ;)

### CODE REVIEW

**Comment by michaelmcmillan** [comment]
Amazing! A lot easier on the eyes 👍  Do you have a screenshot of how it looks right now? Before/after kind of

**Comment by adriaandotcom** [comment]
Added!

**Comment by fossecode** [comment]
Looking good! 👍

**Review by fossecode — APPROVED** [review]

**Comment by michaelmcmillan** [comment]
looks great!

**Pull request merged**
