### PR TITLE
Switch to Stadia Maps.

### PR DESCRIPTION
**Pull request by lseelenbinder**
Switches map integration to use Stadia Maps.

I'll need to know what TLDs we want to allow so we can whitelist those in our system.

### CODE REVIEW

**Comment by adriaandotcom** [comment]
For now I know of

- coronastatus.it
- coronastatus.es
- coronastatus.be
- coronastatus.fr
- coronastatus.nl
- coronastatus.no
- coronastatus.eu
- coronastatus.dk
- coronastatus.ie
- coronastatus.cz
- coronastatus.co.uk
- coronastatus.pt

**Review by fossecode — APPROVED** [review]
Awesome!

**Comment by lseelenbinder** [comment]
- [x] coronastatus.it
- [x]  coronastatus.es
- [x]  coronastatus.be
- [x]  coronastatus.fr
- [x]  coronastatus.nl
- [x]  coronastatus.no
- [x]  coronastatus.eu
- [x]  coronastatus.dk
- [x]  coronastatus.co.uk

**Comment by michaelmcmillan** [comment]
This is very generous of you, thank you so much!

**Comment by adriaandotcom** [comment]
Updated the list above @lseelenbinder! And indeed, thanks a lot!

**Comment by lseelenbinder** [comment]
- [x] coronastatus.ie
- [x] coronastatus.cz
- [x] coronastatus.pt

**Comment by michaelmcmillan** [comment]
@lseelenbinder Just tested this, looks great! Want me to merge?

**Comment by lseelenbinder** [comment]
Go for it @michaelmcmillan!

Still need to add those last few domains, but I don't think it matters much at the moment?

**Comment by adriaandotcom** [comment]
> Still need to add those last few domains, but I don't think it matters much at the moment?

There DNS is not fixed yet, so no problem!

**Pull request merged**
