### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by jelbazi**
Translations for the statistics page (incl locales).

### CODE REVIEW

**Comment by Kilian** [comment]
The text in the .ejs files needs to be wrapped in the translation function for them to work (see 404.ejs for an example), like this:

`<%= __(‘your text’) %>`

**Comment by jelbazi** [comment]
Ah, all text needs to be wrapped, I'm sorry, was under the impression that it just string matched. I'm not familiar with multilanguage libraries.

**Comment by Kilian** [comment]
No worries! If you wanna update it, great! Else I’ll do it later today :)

**Comment by jelbazi** [comment]
I updated all except a handful that contain methods (dynamic data). I don't have enough experience with ES to do those correctly quickly. So if you can do those it'd be better I think.
Lmk what you think.

**Comment by Kilian** [comment]
merged this manually due to conflicts. Thanks @jelbazi!

**Pull request closed without merging**
