### PR TITLE
Australia

### PR DESCRIPTION
**Pull request by bitbonsai**

### CODE REVIEW

**Comment by fossecode** [comment]
Could you delete `app/.DS_Store`? Thanks 🙂

**Comment by fossecode** [comment]
Do you want to use the existing english texts? In that case, could you have a look at this PR?https://github.com/BustByte/coronastatus/pull/351

Otherwise you need to add `au.json` with translations as well.

**Review by fossecode — CHANGES_REQUESTED** [review]
Look at comments above

**Comment by bitbonsai** [comment]
> Do you want to use the existing english texts? In that case, could you have a look at this PR?#351
> 
> Otherwise you need to add `au.json` with translations as well.

I'm adding a `au.json` just in case we want to change some strings in the future... thanks for the headsup! 👍

**Comment by bitbonsai** [comment]
Closing this one because I'm getting new weird errors. Will branch it out and do the localization again with the fixes from above reviews.

**Pull request closed without merging**
